//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exceptions.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesExceptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceMessagesExceptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Exceptions.Exceptions.ResourceMessagesExceptions", typeof(ResourceMessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string EMAIL_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_CADASTRADO", resourceCulture);
            }
        }

        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }

        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }

        public static string INVALID_ROLE {
            get {
                return ResourceManager.GetString("INVALID_ROLE", resourceCulture);
            }
        }

        public static string INVALID_STATUS {
            get {
                return ResourceManager.GetString("INVALID_STATUS", resourceCulture);
            }
        }

        public static string MINIMAL_REGISTRATION_CHARACTER {
            get {
                return ResourceManager.GetString("MINIMAL_REGISTRATION_CHARACTER", resourceCulture);
            }
        }

        public static string MINIMUM_CHARACTER {
            get {
                return ResourceManager.GetString("MINIMUM_CHARACTER", resourceCulture);
            }
        }

        public static string PASS_CHARACTER_ESPETIAL {
            get {
                return ResourceManager.GetString("PASS_CHARACTER_ESPETIAL", resourceCulture);
            }
        }

        public static string PASS_EMPTY {
            get {
                return ResourceManager.GetString("PASS_EMPTY", resourceCulture);
            }
        }

        public static string PASS_MINIMAL_CHARACTER {
            get {
                return ResourceManager.GetString("PASS_MINIMAL_CHARACTER", resourceCulture);
            }
        }

        public static string REGISTRATION_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("REGISTRATION_ALREADY_REGISTERED", resourceCulture);
            }
        }

        public static string SPECIAL_CHARACTER_PASS {
            get {
                return ResourceManager.GetString("SPECIAL_CHARACTER_PASS", resourceCulture);
            }
        }
        
        
        public static string DECRETO_SOLICITANTE_EMPTY {
            get { return ResourceManager.GetString("DECRETO_SOLICITANTE_EMPTY", resourceCulture); }
        }

        public static string DECRETO_SOLICITANTE_MIN_CHARACTER {
            get { return ResourceManager.GetString("DECRETO_SOLICITANTE_MIN_CHARACTER", resourceCulture); }
        }

        public static string DECRETO_DATA_INVALID {
            get { return ResourceManager.GetString("DECRETO_DATA_INVALID", resourceCulture); }
        }

        public static string DECRETO_SECRETARIA_INVALID {
            get { return ResourceManager.GetString("DECRETO_SECRETARIA_INVALID", resourceCulture); }
        }

        public static string DECRETO_JUSTIFICATIVA_EMPTY {
            get { return ResourceManager.GetString("DECRETO_JUSTIFICATIVA_EMPTY", resourceCulture); }
        }
        
        
    }
}
