namespace App.Domain.Enums;

public enum Secretaria
{
    PROCURADORIA_GERAL,
    CASA_CIVIL,
    GOVERNO_E_RELACOES_INSTITUCIONAIS,
    CONTROLADORIA_GERAL,
    SEGURANCA_E_DEFESA_SOCIAL,
    FAZENDA,
    ADMINISTRACAO_E_INOVACAO,
    ARTICULACAO_REGIONAL,
    PLANEJAMENTO_E_PARCERIAS_ESTRATEGICAS,
    LICITACOES_E_CONTRATOS,
    INFRAESTRUTURA_E_SERVICOS_PUBLICOS,
    MEIO_AMBIENTE_E_DESENVOLVIMENTO,
    EDUCACAO,
    SAUDE,
    ASSISTENCIA_SOCIAL_E_CIDADANIA,
    EXECUTIVA_DA_MULHER,
    EXECUTIVA_DA_JUVENTUDE,
    INSTITUTO_PREVIDENCIA,
    AGENCIA_HABITACAO,
    AGENCIA_MEIO_AMBIENTE,
    AGENCIA_REGULACAO,
    AGENCIA_TRANSPORTE_TRANSITO,
    AGENCIA_TECNOLOGIA_INFORMACAO,
    FUNDACAO_CULTURA,
    FUNDACAO_ESPORTES
}
