// <auto-generated />
using System;
using App.Infrastructure.Data.DbConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304200835_FixNumeroDecretoDefault")]
    partial class FixNumeroDecretoDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "secretaria_enum", "secretaria", new[] { "procuradoria_geral", "casa_civil", "governo_e_relacoes_institucionais", "controladoria_geral", "seguranca_e_defesa_social", "fazenda", "administracao_e_inovacao", "articulacao_regional", "planejamento_e_parcerias_estrategicas", "licitacoes_e_contratos", "infraestrutura_e_servicos_publicos", "meio_ambiente_e_desenvolvimento", "educacao", "saude", "assistencia_social_e_cidadania", "executiva_da_mulher", "executiva_da_juventude", "instituto_previdencia", "agencia_habitacao", "agencia_meio_ambiente", "agencia_regulacao", "agencia_transporte_transito", "agencia_tecnologia_informacao", "fundacao_cultura", "fundacao_esportes" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "usuario_role_enum", "usuario_role", new[] { "gestor", "usuario" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "usuario_status_enum", "usuario_status", new[] { "ativo", "inativo" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("decreto_numero_seq")
                .StartsAt(5966L);

            modelBuilder.Entity("App.Domain.Decreto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataParaUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroDecreto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('decreto_numero_seq')");

                    b.Property<int>("Secretaria")
                        .HasColumnType("integer");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Decretos");
                });

            modelBuilder.Entity("App.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Matricula")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("App.Domain.Decreto", b =>
                {
                    b.HasOne("App.Domain.Usuario", "Usuario")
                        .WithMany("Decretos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("App.Domain.Usuario", b =>
                {
                    b.Navigation("Decretos");
                });
#pragma warning restore 612, 618
        }
    }
}
